version: '3.0'
services:
  db:
    container_name: postgres
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_value:/var/lib/pgadmin_data/
    env_file:
      - ./.env


  backend:
    image: ekbtoys/social:v2
    container_name: social
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: ekbtoys/social_frontend:v2
    container_name: social_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./smax.crt:/etc/ssl/smax.crt
      - ./smax.key:/etc/ssl/smax.key
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend
      - backend

  redis:
      image: redis:7.0.5-alpine
      hostname: redis
  
  celery:
    image: ekbtoys/social:v2
    hostname: worker
    command: celery -A social worker -l INFO
    volumes:
      - media_value:/backend/media/
    links:
      - redis
    depends_on:
      - redis
      - db
    env_file:
     - ./.env

  celery-beat:
    image: ekbtoys/social:v2
    hostname: flower
    command: celery -A social beat -l info
    volumes:
      - media_value:/backend/media/
    env_file:
     - ./.env
    depends_on:
      - redis
  
  flower:
    image: ekbtoys/social:v2
    command: celery -A social flower
    volumes:
      - media_value:/backend/media/
    env_file:
     - ./.env
    links:
      - redis
    depends_on:
      - redis
    ports:
      - 5555:5555

volumes:
  postgres_data:
  pgadmin_value:
  static_value:
  media_value:
